name: CI Build
on:
  pull_request:
    branches: [ 'develop-kp' ]
  push:
    branches: [ 'develop-kp' ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        scala: ["2.12", "3"]
        platform: ["JVM"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v6

      - name: Cache build
        uses: coursier/cache-action@v8

      - name: Install coursier
        uses: coursier/setup-action@v3
        with:
          jvm: adoptium:1.21.0.1
          apps: sbt
      - uses: sbt/setup-sbt@v1

      - name: Clean
        run: sbt $SBT_JAVA_OPTS -v "cleanScoped ${{ matrix.scala }} ${{ matrix.platform }}"

      - name: Compile
        run: sbt $SBT_JAVA_OPTS -v "compileScoped ${{ matrix.scala }} ${{ matrix.platform }}"

      - name: Test
        run: sbt $SBT_JAVA_OPTS -v "testScoped ${{ matrix.scala }} ${{ matrix.platform }}"

      - name: Scalafmt check sbt
        if: matrix.os == 'ubuntu-latest' && matrix.scala == '2.12' && matrix.platform == 'JVM'
        run: sbt $SBT_JAVA_OPTS -v scalafmtSbtCheck

      - name: Scalafmt check sources
        if: matrix.os == 'ubuntu-latest'
        run: sbt $SBT_JAVA_OPTS -v "scalafmtCheckScoped ${{ matrix.scala }} ${{ matrix.platform }}"
